### PR TITLE
Requesting code review for Positioning and floating elements project.

### PR DESCRIPTION
**Pull request by gabrie-lhilarion**
## NEW YORK TIMES ARTICLE PAGE CLONE
  * Created navbar corresponding links and logo.
  * Embedded photos and videos
  * Used CSS GRID for article description
  * Flexbox for positioning of elements on the footer.
  * Used floating and clearing to design the articles with embedded images.
  
## Please Note:
* Stickler CI and web API failed to load in this repo and GitHub account despite any efforts and troubleshooting.
* However we installed the Stylelint linter locally for CSS linting and tidy-HTML for HTML files.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Hi @gabrie-lhilarion and @edieatha 👏 👏 
### Well done team, you have done a good job 💪 but you still need to add some requirements before the project can be approved.

**_1.  Enable stickler for the project: I read your pull request message about stickler but this is part of the requirement try to find a way to make it work 🙏.  Put the stickler or lint files in the root directory of the project, not in any folder_**

**_2. The NY Times logo should be a link_** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**_3. Fix the subscribe and login buttons_** 👇 
**_your version_**
image

**_the original_**
image

**_4. The More in science section, Editor's pick section and Most popular section should contain links to other articles with image previews on the leftmost side_** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**_5. The Navbar should have a fixed position_** (it sticks to the top part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**_6. The footer should have a fixed position like the original _** 👇 (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

newyork times

**_7. Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`)_** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**_8. Follow the basic Html semantic structure:_** `<header></header> <main></main> <footer></footer>` **_header will contain nav and other content in the top of the page and main with contain main content of the page and footer will contain footer content of the page._**

**_9. [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) should be use for `Editor's picks` section on the righmost side._** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

**_if you have any doubts or questions contact me on slack._**

### Reviewed by _Temitayo Adeleke_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes

**Comment by edieatha** [comment]
## TSE Review Comments & Corrections Applied
1. Stickler failed to work! Please see comment below. Student success was notified.
2. New York times logo was made a link
3. Fixed subscribe and login buttons
4. Added links to sections More, Editor's Pick and Most popular with image previews
5. Navbar is now in FIXED position
6. Footer is also in FIXED position
7. Project unrelated files removed or added to .gitignore.
8. Followed HTML semantic structure HEAD, MAIN and FOOTER.
9. ASIDE tag used in Editor's Pick.

# NOTE:
Hello there. SticklerCI will not load my repositories and as a result, I have failed to use it on my repositories in Github. The SticklerCI API/Redirect to repositories just wont respond. All I get is the "Login with Github" page nothing more! I have tried several browsers, VPN even changed internet providers but it simply wont work on my repos, and I cant login with GitHub. Any ideas or help would be appreciated. because am having trouble with the TSE's insisting that stickler CI on the Pull requests is a must.  

* However I have been able to install linters locally as suggested by my mentor (Slack @Sebastian Gil Rodriguez)

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @edieatha and @gabrie-lhilarion 
### You have done a good job so far and for also implementing reviews from the previous review :clap: However, you have a few more issues to solve.
- Align your image and video in the article with the rest of the content
image not aligned
video not aligned
- Your sidebar is missing some content refer the original website
sidebar
- Don't change the font example in the footer, refer to the original design
font
### Make these changes and resubmit for another code review. Good luck.
- Happy coding!

**Comment by edieatha** [comment]
## TSE Code Review Corrections Applied
1. Aligned video and image with article text
2. Fixed missing text in Editor's Pick
3. Fixed footer font formatting

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️  🚥 

Hi **TEAM**, you have done a great job 👍 To approve the project, we need to fix the changes pointed out by the other TSE's. I will therefore highlight it again so we can fix it. Find comments below:
- Stickler must be enabled on the repo. A quick fix is to visit stickler-ci.com and enable stickler for the repo
- Let us add links to where we were asked to add. Refer previous comments
ny2
- I found some of the images not appearing
ny
ny1

Kindly make these changes and submit another code review 👍 
Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by edieatha** [comment]
## TSE Review Comments & Corrections Applied
1. Stickler wont work on Github Account and Repositories SEE Note Below
2. Added Links to artciles in most popular, editor picks, and more space sections
3. Fixed missing images.

# NOTE:
Hello there. SticklerCI will not load my repositories and as a result, I have failed to use it on my repositories in Github. The SticklerCI API/Redirect to repositories just wont respond. All I get is the "Login with Github" page nothing more! I have tried several browsers, VPN even changed internet providers but it simply wont work on my repos, and I cant login with GitHub. Any ideas or help would be appreciated. because am having trouble with the TSE's insisting that stickler CI on the Pull requests is a must.  

* However I have been able to install linters locally as suggested by my mentor (Slack @Sebastian Gil Rodriguez)

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @edieatha  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
I am truly sorry that you are having problems with the stickler linter. I have read your issue but for some reason, it is not conclusive enough. Kindly expound more why a log-in with GitHub account is impossible. is your partner also experiencing the same? Maybe they could be of helo on how they did theirs.
## REQUIRED CHANGES
- [ ] In line with the checks that need to be passed in order for the project to be approved, your CSS files must pass the stickler check.
- [ ] Validate your markup as well to fix the warnings currently present.
- [ ] The social icons are still not showing in the page.
- This is what I am seeing: 👇 
icon_clone
- [ ] The editor's pick section is not properly positioned as in the original. Kindly fix that as well.
editors_pick_clone
- [ ] Also fix the theory of inflation section. It is not rendering properly in large screens.
- This is what I am seeing: 👇 
theory_of_inflation
##
Please make the suggested changes and submit another review request.

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by edieatha** [comment]
## CHANGES MADE
1. Validated HTML File
2. Fixed Editor's Pick section
3. Fixed theory of inflation section
4. Fixed icons that didn't display

## STICKLER
1. As mentioned earlier Stickler will not work on my GutHub repos for some reason beyond my comprehension.
2. I have registered with my GitHub account at Stickler-Ci.com and granted access to stickler.
3. For some technical reason its not working even after adding '.stickler.yml' files and 'stylelint.config' files.
4. I can't access the stickler-ci.com/repo page the only page I see is the "Login with Github Page".
Once I click the button, the page isn't redirected it's stuck on the Login page.
4. Screenshots below.

## Stickler granted access:

Screenshot_2020-04-09 Build software better, together(1)

## No stickler app showing up in Authorized Apps:
Screenshot_2020-04-09 Build software better, together

## Stickler XML & CONFIG Files added to root folder.
Screenshot_2020-04-09 edieatha newyorktimes

## Buggy Stickler Page. Not redirecting to repos page.
Screenshot_2020-04-09 Stickler CI Users


# This issue has been forwarded to student success with no replies.

**Pull request merged**
